deployments/urls.py
from django.conf.urls import patterns, include, url

# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    

    url(r'^add-project$', 'deployments.views.projects.add_project', name='add-project'),
    
    # url(r'^', 'frontend.views.home.home',name='home'),
    
    url(r'^project/(?P<project_id>\d*)$','deployments.views.projects.project', name="project"),
    url(r'^project/(?P<project_id>\d*)/add-hook$','deployments.views.hooks.add_hook', name="add-hook"),
    url(r'^project/edit-hook/(?P<hook_id>\d*)$','deployments.views.hooks.edit_hook', name="edit-hook"),
    
    url(r'^project/(?P<project_id>\d*)/add-deployment$', 'deployments.views.deploy.add_deployment', name='add-deployment'),
    url(r'^project/(?P<project_id>\d*)/delete$', 'deployments.views.projects.delete_project', name='delete_project'),
    url(r'^deployment/(?P<deployment_id>\d*)/edit$', 'deployments.views.deploy.edit_deployment', name='edit-deployment'),
    url(r'^deployment/(?P<deployment_id>\d*)/delete$', 'deployments.views.deploy.delete_deployment', name='delete_deployment'),
    url(r'^deployment/(?P<deployment_id>\d*)/run$', 'deployments.views.deploy.run_deployment', name='run-deployment'),
    url(r'^deployment/(?P<deployment_id>\d*)/past-deployments$', 'deployments.views.deploy.past_deployments', name='show-past-deployments'),


    #url(r'^deployment/(?P<deployment_id>\d*)/git_test$', 'deployments.views.deploy.git_test', name='git-test-deployment'),

    url(r'^test-connection$','deployments.views.deploy.test_connection', name="test_connection"),

    
    url(r'^hook/(?P<hook_id>\d*)/run/(?P<key>\w*)$', 'deployments.views.deploy.run_hook', name="run-hook"),
    url(r'^hook/(?P<hook_id>\d*)/delete$', 'deployments.views.hooks.delete_hook', name="delete_hook"),
    
    
    # url(r'^admin/', include(admin.site.urls)),
)

frontend/urls.py
from django.conf.urls import patterns, include, url

# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'frontend.views.default.index', name='index'),

    url(r'^login$', 'frontend.views.default.login', name='login'),
    # url(r'^', 'frontend.views.home.home',name='home'),
    
    url(r'^logout$', 'frontend.views.default.logout', name='logout'),

	url(r'^profile$', 'frontend.views.profile.profile', name='profile'),
	url(r'^profile/validate_token$', 'frontend.views.profile.validate_token', name='validate_token'),
    

    
    
    # url(r'^admin/', include(admin.site.urls)),
)

gitlab_deployment/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gitlab_deployment.views.home', name='home'),
    url(r'^', include('frontend.urls')),

    url(r'^deployments/',include('deployments.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^jsreverse/$', 'django_js_reverse.views.urls_js', name='js_reverse'),

)

deployments/models.py
from django.db import models
from django.contrib.auth.models import User
import django.dispatch
from django.conf import settings
from django_extensions.db.fields.encrypted import *
import random, re
from django.core.urlresolvers import reverse
import urllib, hashlib
from django.conf import settings
from django.db.models.signals import post_delete
import shutil


# Create your models here.


class UserSettings(models.Model):

    user = models.OneToOneField(User, related_name='settings')
    gitlab_token = models.CharField(max_length = 200, default = None, blank=True, null = True)


    @property
    def profile_picture(self):
        size = 40
        email = self.user.email
        gravatar_url = "http://www.gravatar.com/avatar/" + hashlib.md5(email.lower()).hexdigest()
        return gravatar_url



class Project(models.Model):

    name = models.CharField(max_length=250)
    creator = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)

    
    gitlab_id = models.IntegerField(max_length = 10)


    def get_git_url(self):
        pass


    def __unicode__(self):
        return self.name


    # signals
    project_created = django.dispatch.Signal(providing_args=["project"])


class Deployment(models.Model):

    name = models.CharField(max_length=250)
    creator = models.ForeignKey(User) 
    created_at = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project, related_name="deployments")

    host = models.CharField(max_length = 500)
    username = models.CharField(max_length = 500)
    password = EncryptedCharField(max_length = 500, blank=True)
    #port = models.IntegerField(max_length =6, default = 22)
    shell_code = models.TextField(max_length = 500, blank=True)


    FTP_SYNC = "FTP"
    SSH_SCRIPT = "SSH"
    DEPLOYMENT_TYPES = (
            (FTP_SYNC, "FTP synchronisation"),
            (SSH_SCRIPT, "SSH script")
        )


    deployment_type = models.CharField(max_length=10, choices=DEPLOYMENT_TYPES, default = SSH_SCRIPT)

    last_revision = models.CharField(max_length=260, default = "", blank=True)
    ftp_home_dir = models.CharField(max_length = 200, blank=True)


    def get_repository_root(self):
        return settings.REPOSITORY_ROOT + str(self.id)



    def get_last_run(self):
        return DeploymentExecution.objects.filter(deployment=self).order_by('-run_at')[:1].get()    

    @property
    def last_run_successful(self):
        lr = self.get_last_run()

        if lr:
            return lr.success

        return False

    @property
    def last_run_at(self):
        lr = self.get_last_run()

        if lr:
            return lr.run_at

        return False


    def __unicode__(self):
        return self.name

    def save_execution(self, success, output, hook = None, invoked_by = None):

        exe = DeploymentExecution()
        exe.deployment = self
        exe.invoked_by = invoked_by
        exe.success = success
        exe.output = output
        exe.hook = hook
        exe.save()

        print "saved"


def delete_repository_if_existent(sender, **kwargs):
    try:
        deployment = kwargs['instance']    
        shutil.rmtree(deployment.get_repository_root())
    except:
        # we don't have a dir to delete
        pass



post_delete.connect(delete_repository_if_existent, Deployment)




class DeploymentExecution(models.Model):

    class Meta:
        ordering = ['-run_at']

    deployment = models.ForeignKey(Deployment, related_name='executions')
    run_at = models.DateTimeField(auto_now_add=True)
    invoked_by = models.ForeignKey(User, null=True, blank=True)
    success = models.BooleanField()
    output = models.TextField()
    hook = models.ForeignKey("Hook", blank=True, null=True)

    @property
    def manual(self):
        return hook is None


KEY_LENGTH = 30

def gen_key(length=KEY_LENGTH):
    legal_chars = ['1', '2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','J','K','M','N','P','Q','R','S','T','U','V','W','X','Y','Z','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    key = ''
    for i in range(length):
        key+= random.choice(legal_chars)
    return key




class Hook(models.Model):

    def save(self, *args, **kwargs):
        key = self.key
        while key == u"":
            try:
                key = gen_key()
                print key
                Hook.objects.get(key=key)
                key = u""
            except Hook.DoesNotExist:
                pass #expected
        self.key = key
        super(Hook, self).save(*args, **kwargs)  

    name = models.CharField(max_length=200)
    every_push = models.BooleanField(default = False, help_text="If checked, the hook gets executed on every push.")
    commit_message_regex = models.CharField(max_length=250, null=True, blank=True)
    project = models.ForeignKey(Project, related_name='hooks', null=True, blank=True)
    deployments = models.ManyToManyField(Deployment, related_name='hooks', help_text="Select the deployments you want to be executed within this hook.<br>")

    creator = models.ForeignKey(User, null=True) 
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    key = models.CharField(max_length=200, unique = True)

    def regex_matches(self, commit_message):
        reg = self.commit_message_regex

        if not re.search(reg, commit_message):
            return False
        else:
            return True


        pass

    def get_absolute_url(self):
        return reverse('run-hook',args=[self.id, self.key])


    def __unicode__(self):
        try:
            return self.deployments.all()[0].name
        except:
            return "NO DEPLOYMENT"

deployments/views/deploy.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import Http404

from django.contrib.auth.decorators import login_required

from deployments.models import *
from django.views.decorators.csrf import csrf_exempt


from django.contrib import messages

from django.forms import ModelForm

from django.forms.models import modelform_factory

import django.dispatch

from deployments.deployment_runner import *

from django.http import HttpResponse

import deployments.ftp_synchronizer as ftp_sync
import ftputil
from fabric.api import *


DeploymentForm = modelform_factory(Deployment, fields=("name","deployment_type","host","username","password","ftp_home_dir", "shell_code"))


@login_required
def add_deployment(request, project_id):


    try:
        p = Project.objects.get(id=project_id)
    except:
        raise Http404

    if (request.method == "POST"):

        form = DeploymentForm(request.POST)

        if form.is_valid():
            deployment = form.save(commit =False)
            deployment.creator = request.user
            deployment.project_id = project_id
            
            deployment.save()

            
            messages.add_message(request, messages.SUCCESS, "Deployment <i>"+deployment.name+"</i> created")
            return redirect(reverse('project', args=[project_id])+'#deployment-'+str(deployment.id))
            
            pass

    else:
        form = DeploymentForm()

    return render(request,"add_deployment.html", {'form':form, 'project':p})



@login_required
def edit_deployment(request, deployment_id):


    try:
        d = Deployment.objects.get(id=deployment_id)
        p = d.project
    except:
        pass

    if (request.method == "POST"):

        form = DeploymentForm(request.POST, instance=d)

        if form.is_valid():
            deployment = form.save(commit =True)
            
            messages.add_message(request, messages.SUCCESS, "Deployment <i>"+deployment.name+"</i> saved")

            
            pass

    else:
        form = DeploymentForm(instance=d)

    return render(request,"edit_deployment.html", {'form':form, 'project':p})



@login_required
def run_deployment(request, deployment_id):

    (success, output) = run_deployment_by_id(deployment_id)

    deployment = Deployment.objects.get(id=deployment_id)

    deployment.save_execution(success, output, None, request.user)

    return HttpResponse("<pre>"+output+"</pre>")

@csrf_exempt
def test_connection(request):

    user = request.POST['user']
    host = request.POST['host']
    password = request.POST['password']
    deployment_type = request.POST['type']
    ftp_home_dir = request.POST['ftp_home_dir']

    success = True

    if deployment_type == Deployment.SSH_SCRIPT:
        print "SSH"

        try:
            with settings(host_string=host, user=user, password=password, abort_on_prompts=True):
                
                try:
                    res = run('echo "test"')
                except:
                    success = False



        except:
            success = False

    elif deployment_type == Deployment.FTP_SYNC:

        try:
            host = ftputil.FTPHost(host, user, password)
            host.chdir(ftp_home_dir)
        except:
            success = False



    resp = "1"

    if not success:
        resp = "0"

    return HttpResponse(resp)
        



@login_required
def past_deployments(request, deployment_id):

    d = Deployment.objects.get(id=deployment_id)

    return render(request, "past_deployments.html", {'deployment':d})  


@csrf_exempt
def run_hook(request, hook_id, key):

    hook = Hook.objects.get(id=hook_id, key=key)

    (s, o) = execute_hook(hook, request)

    return HttpResponse(o)





def git_test(request, deployment_id):

    deployment = Deployment.objects.get(id=deployment_id)
    (success, res) = ftp_sync.synchronize_deployment(deployment, request)


    return HttpResponse(res)


@login_required
def delete_deployment(request, deployment_id):

    
    p= Deployment.objects.get(id=deployment_id)
    p.delete()
    
    return HttpResponse("1")    

deployments/views/hooks.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required

from deployments.models import *


from django.contrib import messages

from django.forms import ModelForm

from django.forms.models import modelform_factory

import django.dispatch
import gitlab
from django.conf import settings
from django.http import HttpResponse


# HookForm = modelform_factory(Hook, fields=("every_push","commit_message_regex","deployments"))

class HookForm(ModelForm):

    class Meta:
        model = Hook
        fields = ("name","every_push","commit_message_regex","deployments")

    def __init__(self, *args, **kwargs):
        
        current_project_id = kwargs.pop('current_project_id')
        print current_project_id
        super(HookForm, self).__init__(*args, **kwargs)

        self.fields['deployments'].queryset = Deployment.objects.filter(project_id=int(current_project_id))
    

@login_required
def add_hook(request, project_id):


    if (request.method == "POST"):

        form = HookForm(request.POST, current_project_id= project_id)

        if form.is_valid():
            hook = form.save(commit =True)
            hook.creator = request.user
            hook.project_id = project_id
            hook.save()

            register_hook = False

            try:
                tmp = request.POST['id_register_hook']
                register_hook = True
            except:
                pass

            if register_hook:
                git = gitlab.Gitlab(settings.GITLAB_URL, request.user.settings.gitlab_token)
                url_hook = request.build_absolute_uri(hook.get_absolute_url())

                if git.addprojecthook(hook.project.gitlab_id, url_hook, push=True):
                    messages.add_message(request, messages.SUCCESS, "Hook registered in GitLab")
                else:
                    messages.add_message(request, messages.ERROR, "Hook could not be registered")
                


            
            #project.project_created.send(sender=project, project = project)
            messages.add_message(request, messages.SUCCESS, "Hook for project <i>"+hook.project.name+"</i> created")
            return redirect(reverse("project",args=[project_id]))

            pass

    else:
        form = HookForm(current_project_id=project_id)

    return render(request,"add_hook.html", {'form':form})


@login_required
def edit_hook(request, hook_id):
    
    d = Hook.objects.get(id=hook_id)

    url = request.build_absolute_uri(d.get_absolute_url())

    if (request.method == "POST"):

        form = HookForm(request.POST, instance=d, current_project_id=d.project_id)

        if form.is_valid():
            hook = form.save(commit =True)
            
            messages.add_message(request, messages.SUCCESS, "Hook for project <i>"+hook.project.name+"</i> saved")
            
            pass

    else:
        form = HookForm(instance=d, current_project_id=d.project_id)

    return render(request,"edit_hook.html", {'form':form, 'hook':d, 'project':d.project, 'url':url})

@login_required
def delete_hook(request, hook_id):

    
    p= Hook.objects.get(id=hook_id)
    p.delete()
    
    return HttpResponse("1")    

deployments/templates/add_deployment.html
{% extends "add_edit_deployment_base.html" %}



{% block deployment_mode_title %}
    Add Deployment
{% endblock deployment_mode_title %}

{% block deployment_button_title %}
    Create Deployment
{% endblock deployment_button_title %}

deployments/templates/add_edit_deployment_base.html
{% extends "base.html" %}



{% load staticfiles %}

{% load bootstrap3 %}


{% block body_class %}deployment{% endblock body_class %}

{% block content %}
    
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-lg-offset-3">

            <h3>{{project.name}} <a href="{% url 'project' project.id %}" class="btn btn-info btn-sm pull-right">Back to Project</a> </h3>
            
             <h4>
             	{% block deployment_mode_title %}{% endblock deployment_mode_title %}
             </h4>   



            <form method="POST" class="form">
                
            {% csrf_token %}
            {% bootstrap_form form %}

            
            <button type="button" class="btn btn-info pull-left check-connection-settings">Check Connection Settings</button>

            <button type="submit" class="btn btn-primary pull-right" >
            {% block deployment_button_title %}
            	
            {% endblock deployment_button_title %}
        </button>

            </form>


            <div class="clearfix"></div>

             <div class="alert alert-warning"><b>Warning!</b> Currently the execution of shell code on remote machines is <b>stateless</b>. That means that you have to <i>cd</i> in directories in every single line, etc.
             <pre>
$ cd test && pwd
/home/dummy/test

$ pwd
/home/dummy</pre>
             </div>             

            

            </div>
            
        </div>
    </div>

{% endblock content %}





{% block extra_script %}
	
	<script type="text/javascript">
		$(function(){




			function changeView(){
				var type = $('#id_deployment_type');

				var elements_to_show = [];
				var elements_to_hide = [];

				if(type.val()=="FTP"){
					elements_to_show.push($('#id_ftp_home_dir'));
					elements_to_hide.push($('#id_shell_code'));
				}	

				if(type.val()=="SSH"){
					elements_to_hide.push($('#id_ftp_home_dir'));
					elements_to_show.push($('#id_shell_code'));
				}


				$.each(elements_to_hide, function(i,e){
					e.parent().hide();
				});

				$.each(elements_to_show, function(i,e){
					e.parent().show();
				});


			}

			changeView();

			$('#id_deployment_type').change(changeView);







			$('.check-connection-settings').click(function(){

				$('.check-connection-settings').button('loading');

				var user = $('#id_username').val();
				var host = $('#id_host').val();
				var password = $('#id_password').val();
				var ftp_home_dir = $('#id_ftp_home_dir').val();
				var type = $('#id_deployment_type').val();

				


				$.post(Urls.test_connection(), {
					'user':user,
					'host':host,
					'password':password,
					'ftp_home_dir':ftp_home_dir,
					'type':type
				}, function(res){
					$('.check-connection-settings').button('reset');
					$('.check-connection-settings').removeClass("btn-info");
					$('.check-connection-settings').removeClass("btn-success");
					$('.check-connection-settings').removeClass("btn-danger");
					if(res == 1){

						$('.check-connection-settings').addClass("btn-success");
						

					}else{
						$('.check-connection-settings').addClass("btn-danger");
						
					}
				});

			});
		});
	</script>

{% endblock extra_script %}

deployments/templates/add_hook.html
{% extends "base.html" %}

{% load staticfiles %}

{% load bootstrap3 %}


{% block body_class %}hook{% endblock body_class %}

{% block content %}
    
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-lg-offset-3">

            <h1>{{project.name}} <a href="{% url 'project' project.id %}" class="btn btn-info btn-sm pull-right">Back to Project</a> </h1>
            
             <h2>Add new Hook</h2>   
            <div class="alert alert-info">
             
                 
                     <strong>Remember:</strong> The commit message regular expression <i>is</i> an actual regular expression. So if you want to match e.g. 
                     <pre>did this and that [deploy]</pre>
                     you have to write your regexp like
                     <pre>\[deploy\]</pre>
                 
                 
             </div>


            <form method="POST" class="form">
                
            {% csrf_token %}
            {% bootstrap_form form %}

            <div class="form-group">
                <div class="checkbox">
                    <label title="You can also do this later manually.">
                        <input id="id_register_hook" name="id_register_hook" class="" type="checkbox" name="register_hook">
                        Register Hook in GitLab
                    </label>
                </div>
                <span class="help-block">You can also do this later manually.</span>
                
            </div>

            <button type="submit" class="btn btn-primary pull-right" >
            {% bootstrap_icon "plus" %} Create Hook
        </button>

            </form>

            </div>
            
        </div>
    </div>

{% endblock content %}

deployments/templates/add_project.html
{% extends "base.html" %}

{% load staticfiles %}

{% load bootstrap3 %}


{% block content %}
    
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-lg-offset-3">
            
             <h2>Add new Project</h2>   


            <form method="POST" class="form">
                
            {% csrf_token %}

            {% bootstrap_form form %}

            <a class="btn btn-info pull-left add-repo" href="{{ project_settings.GITLAB_URL }}/projects/new" target="_blank"><i class="fa fa-git"></i> Add Git Repositoy</a>
            <a class="btn btn-warning pull-left reload" href="#"><i class="fa fa-refresh"></i> Refresh</a>

            <button type="submit" class="btn btn-primary pull-right" >
            {% bootstrap_icon "plus" %} Create Project
        </button>

            </form>

            </div>
            
        </div>
    </div>

{% endblock content %}

{% block extra_script %}
    
    <script type="text/javascript">


        $('#project_select').change(function(){
            var id = $('#project_select').val();
            var label = $('#project_select option:selected').text();

            $('#project_id').val(id);
            $('#project_name').val(label);
        });

        $('#project_select').change();



        $('.reload').hide();

        $('.add-repo').click(function(){
            setTimeout(function(){
                $('.add-repo').hide();
            $('.reload').show();
            },1000);

            
        });

        $('.reload').click(function(){
            window.location.reload();
        });
    </script>

{% endblock extra_script %}

deployments/templates/edit_deployment.html
{% extends "add_edit_deployment_base.html" %}



{% block deployment_mode_title %}
    Edit Deployment
{% endblock deployment_mode_title %}

{% block deployment_button_title %}
     Save Deployment
{% endblock deployment_button_title %}

deployments/templates/edit_hook.html
{% extends "base.html" %}

{% load staticfiles %}

{% load bootstrap3 %}


{% block body_class %}hook{% endblock body_class %}

{% block content %}
    
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-lg-offset-3">

            <h1>{{project.name}} <a href="{% url 'project' project.id %}" class="btn btn-info btn-sm pull-right">Back to Project</a> </h1>
            
             <h2>Edit Hook</h2>   

             <div class="alert alert-info">
             
                 <strong>Hook URL</strong> 
                 <pre>{{url}}</pre>
            </div>
            <div class="alert alert-warning">

                 <p>
                     <strong>Remember</strong> <br>The commit message regular expression <i>is</i> an actual regular expression. So if you want to match e.g. 
                     <pre>did this and that [deploy]</pre>
                     you have to write your regexp like
                     <pre>\[deploy\]</pre>
                 </p>
                 
             </div>



            <form method="POST" class="form">
                
            {% csrf_token %}
            {% bootstrap_form form %}

            <button type="submit" class="btn btn-primary pull-right" >
            {% bootstrap_icon "plus" %} Safe Hook
        </button>

            </form>

            </div>
            
        </div>
    </div>

{% endblock content %}

deployments/templates/past_deployments.html
{% extends "base.html" %}

{% block content %}

<div class="container">

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <a href="{% url 'project' deployment.project.id %}">Back to project</a><br><br>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<div class="panel-group" id="accordion">


{% for execution in deployment.executions.all %}
  <div class="panel panel-default">
    <div class="panel-heading success">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse-{{execution.id}}">
          {{execution.run_at}} 

        </a>
        {% if execution.success %}
            <span class="label label-success pull-right">Success</span>
          {% else %}
            <span class="label label-danger  pull-right">Failure</span>
          {% endif %}
            <span class="pull-right">&nbsp;</span>

        {% if execution.hook %}
          <span class="label label-info pull-right">Hook: {{execution.hook.name}}</span>

          {% else %}
          <span class="label label-default pull-right">Invoked by {{execution.invoked_by}}</span>
        {% endif %}
      </h4>
    </div>
    <div id="collapse-{{execution.id}}" class="panel-collapse collapse in">
      <div class="panel-body">
        <pre>{{execution.output}}</pre>
      </div>
    </div>
  </div>
  
{% endfor %}

</div>  
        
      </div>  
  </div>
</div>

{% endblock content %}


{% block extra_script %}
  
  <script type="text/javascript">
    $('.collapse').collapse();
  </script>

{% endblock extra_script %}